### ISSUE TITLE
Jupyter notebook fails to load - Error 500

### ISSUE THREAD

**Issue by yatesdr** [overhangio/tutor-jupyter#13]
Installed per the instructions, but when adding an "Advanced Module" > Jupyter, get the error below in studio, and a similar error in student view.

<img width="938" alt="image" src="https://github.com/user-attachments/assets/7564b324-f37c-4d00-97e9-e0f0aa374ab9">

I think this may have to do with the proxy configuration, but am not sure how to approach solving it.

The site is hosted on http inside the network, with a reverse proxy / load balancer on a separate machine, per the docs.:
ENABLE_HTTPS: true
ENABLE_WEB_PROXY: false

**Possibly relevant information below:**
Configuration:

1) Fresh install via tutor local
2) Running behind separate NGINX proxy which handles SSL & certs

3) Plugins enabled:
 android    	installed	18.0.0
cairn      	installed	18.0.0
credentials	installed	18.0.0
discovery  	installed	18.0.0
ecommerce  	installed	18.0.0
forum      	installed	18.1.1
indigo     	✅ enabled	18.1.1
jupyter    	✅ enabled	18.1.0
mfe        	✅ enabled	18.0.1
minio      	installed	18.0.0
notes      	installed	18.0.0
webui      	installed	18.0.0
xqueue     	installed	18.0.0

**tutor local logs | grep Jupyter (excerpt):**

caddy-1          | {"level":"info","ts":1728149797.1149762,"logger":"http.log.access.log1","msg":"handled request","request":{"remote_ip":"192.168.13.16","remote_port":"55090","client_ip":"192.168.13.1","proto":"HTTP/1.0","method":"DELETE","host":"cms.edx.martinrea.tech","uri":"/xblock/block-v1:Martinrea+GS-101+ALL_GENERAL+type@jupyter+block@085bf96cfda141cebd2dd412b5fffd14"},"bytes_read":0,"user_id":"","duration":0.283528305,"size":0,"status":204}
caddy-1          | {"level":"info","ts":1728149799.977361,"logger":"http.log.access.log1","msg":"handled request","request":{"remote_ip":"192.168.13.16","remote_port":"60512","client_ip":"192.168.13.1","proto":"HTTP/1.0","method":"GET","host":"cms.edx.martinrea.tech","uri":"/xblock/block-v1:Martinrea+GS-101+ALL_GENERAL+type@jupyter+block@93aef19196444650be3e50276dafe016/reorderable_container_child_preview?_=1728149790950"},"bytes_read":0,"user_id":"","duration":0.110385753,"size":7182,"status":200}
caddy-1          | {"level":"error","ts":1728149800.3044083,"logger":"http.log.access.log1","msg":"handled request","request":{"remote_ip":"192.168.13.16","remote_port":"60538","client_ip":"192.168.13.1","proto":"HTTP/1.0","method":"GET","host":"cms.edx.martinrea.tech","uri":"/preview/xblock/block-v1:Martinrea+GS-101+ALL_GENERAL+type@jupyter+block@93aef19196444650be3e50276dafe016/handler/lti_launch_handler"},"bytes_read":0,"user_id":"","duration":0.145038784,"size":3000,"status":500}

**Browser error shows up in dev tools (Javascript):**

[Error] Failed to load resource: the server responded with a status of 500 (Internal Server Error) (lti_launch_handler, line 0)
[Error] Failed to load resource: the server responded with a status of 500 (Internal Server Error) (lti_launch_handler, line 0)
[Error] Failed to load resource: the server responded with a status of 500 (Internal Server Error) (lti_launch_handler, line 0)
[Error] Failed to initialize Beamer: beamer_config is not defined
	a (beamer-embed.js:1:2610)
	(anonymous function) (beamer-embed.js:1:3257)

**Comment by yatesdr** [comment]
docker ps -a, for further reference:

CONTAINER ID   IMAGE                                   COMMAND                  CREATED          STATUS                      PORTS                                                             NAMES
56edc4207df0   overhangio/openedx:18.1.3-indigo        "celery --app=cms.ce…"   58 minutes ago   Up 40 minutes               8000/tcp                                                          tutor_local-cms-worker-1
d41c77164d5b   overhangio/openedx:18.1.3-indigo        "uwsgi /openedx/uwsg…"   58 minutes ago   Up 40 minutes               8000/tcp                                                          tutor_local-cms-1
5cd8feb4deb6   overhangio/openedx:18.1.3-indigo        "celery --app=lms.ce…"   58 minutes ago   Up 40 minutes               8000/tcp                                                          tutor_local-lms-worker-1
ad14062279df   overhangio/openedx:18.1.3-indigo        "uwsgi /openedx/uwsg…"   58 minutes ago   Up 40 minutes               8000/tcp                                                          tutor_local-lms-1
c84fb274d00a   overhangio/jupyterhub:18.1.0            "jupyterhub"             58 minutes ago   Up 40 minutes               8000/tcp                                                          tutor_local-jupyterhub-1
34b51dd1b8be   caddy:2.7.4                             "caddy run --config …"   16 hours ago     Up 40 minutes               443/tcp, 2019/tcp, 443/udp, 0.0.0.0:81->80/tcp, [::]:81->80/tcp   tutor_local-caddy-1
b9c0519f5a8d   overhangio/openedx-mfe:18.0.1-indigo    "caddy run --config …"   22 hours ago     Up 40 minutes               80/tcp, 443/tcp, 2019/tcp, 443/udp                                tutor_local-mfe-1
7e37a5cd96a4   mongo:7.0.7                             "docker-entrypoint.s…"   22 hours ago     Up 40 minutes               27017/tcp                                                         tutor_local-mongodb-1
009b158d40b0   redis:7.2.4                             "docker-entrypoint.s…"   22 hours ago     Up 40 minutes               6379/tcp                                                          tutor_local-redis-1
4e0d60ed10b0   elasticsearch:7.17.13                   "/bin/tini -- /usr/l…"   22 hours ago     Up 40 minutes               9200/tcp, 9300/tcp                                                tutor_local-elasticsearch-1
f684b91ae8c3   mysql:8.4.0                             "docker-entrypoint.s…"   22 hours ago     Up 40 minutes               3306/tcp, 33060/tcp                                               tutor_local-mysql-1
ebad0a98f99d   overhangio/openedx-permissions:18.1.3   "sh /usr/local/bin/s…"   22 hours ago     Exited (0) 39 minutes ago                                                                     tutor_local-permissions-1
5911d3d94e94   hello-world                             "/hello"                 23 hours ago     Exited (0) 23 hours ago                                                                       youthful_einstein

**Comment by amita-kapoor** [comment]
I am also facing a similar problem. Installed as per the instructions. But when I start the Jupyter Module, I get:
![image](https://github.com/user-attachments/assets/d226472e-e5d8-4227-bbd8-04e89f516b76)

There are  no errors in tutor log.

**Comment by Abdul-Muqadim-Arbisoft** [comment]
Hi @yatesdr @amita-kapoor , I tried to reproduce the issue and was successfully able to make the plugin work. Can you try running `tutor images build jupyterlab` along with the other steps mentioned in the README of the plugin? I think that would be able to resolve your issue. Please let me know after running the command if it resolved your issue.
