### ISSUE TITLE
"no such group: jovyan" error when building jupyterlab

### ISSUE THREAD

**Issue by angonz** [overhangio/tutor-jupyter#9]
When running `tutor images build jupyterlab` I got the following error:

```
Step 8/9 : COPY --chown=jovyan:jovyan ./config.py /tmp/
unable to convert uid/gid chown string to host mapping: can't find gid for group jovyan: no such group: jovyan

```

After adding `RUN groupadd jovyan` in the [lab's docker file](https://github.com/overhangio/tutor-jupyter/blob/3c5b1b4c95d8d84bb8b52588c48b28d18d67ae85/tutorjupyter/templates/jupyter/build/lab/Dockerfile#L7) the error is gone.

**Comment by Abdul-Muqadim-Arbisoft** [comment]
Hi @angonz,

I wasn't able to reproduce this issue with Tutor 18.0.1. Could you please provide me with the following details:

1. The exact version of Tutor you are using.
2. Any additional configurations or customizations you have applied.
3. A step-by-step description of how you setup tutor-jupyter.

This information will help me understand the context better and assist you more effectively.

Thank you!

**Comment by angonz** [comment]
Hi @Abdul-Muqadim-Arbisoft! It's weird... I tried again and now it worked without any modifications. I will close the case and let you know if it happens again.
